services:
  app:
    build:
      context: . # Use current directory as build context
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app # Mount the local app directory to app in the container
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
